import { useEffect, useState } from 'react'

export type Project = {
  _id: string
  slug: string
  name: string
  kind: string
  year: string
  client: string
  services: string[]
  intro: string
  challenge: string
  solution: string
  results: { v: string; l: string }[]
  tint: string
  liveUrl: string
  cover: string
  detail: string
  gallery: string[]
  video: string
  featured: boolean
  published: boolean
  order: number
}

export type Review = {
  _id: string
  who: string
  company: string
  quote: string
  video: string
  poster: string
  published: boolean
  order: number
}

type Envelope<T> = { success: boolean; message: string; data: T }

const TOKEN_KEY = 'cd-admin-token'
export const auth = {
  get: () => { try { return localStorage.getItem(TOKEN_KEY) } catch { return null } },
  set: (t: string | null) => { try { if (t) localStorage.setItem(TOKEN_KEY, t); else localStorage.removeItem(TOKEN_KEY) } catch { /* private mode */ } },
}

/** fetch wrapper: JSON in/out, admin token attached, throws the server's message. */
export async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const headers = new Headers(init.headers)
  if (init.body && !(init.body instanceof FormData)) headers.set('content-type', 'application/json')
  const t = auth.get()
  if (t && path.startsWith('/admin')) headers.set('authorization', `Bearer ${t}`)
  const res = await fetch('/api' + path, { ...init, headers })
  const json = (await res.json().catch(() => null)) as Envelope<T> | null
  if (!res.ok || !json?.success) {
    if (res.status === 401 && path.startsWith('/admin') && path !== '/admin/login') { auth.set(null); dispatchEvent(new Event('cd:logout')) }
    throw new Error(json?.message || `Request failed (${res.status})`)
  }
  return json.data
}

// Public content: fetched once per page load and shared by every component.
const cache = new Map<string, Promise<unknown>>()
function useCached<T>(path: string, fallback: T) {
  const [data, setData] = useState<T | null>(null)
  useEffect(() => {
    let live = true
    if (!cache.has(path)) cache.set(path, api<T>(path).catch(() => fallback))
    ;(cache.get(path) as Promise<T>).then((d) => live && setData(d))
    return () => { live = false }
  }, [path, fallback])
  return data
}
const NONE: never[] = []
export const useProjects = () => useCached<Project[]>('/projects', NONE)
export const useReviews = () => useCached<Review[]>('/reviews', NONE)
/** Call after admin edits so the public pages refetch. */
export const clearCache = () => cache.clear()

// ImageKit optimises on delivery: `tr` asks for a size, format (WebP/AVIF) and compression are automatic.
// Local /uploads and /work files pass through unchanged.
const isIK = (u: string) => /^https:\/\/[^/]*imagekit\.io\//.test(u)
export const ik = (url: string, tr: string) => (url && isIK(url) ? `${url}${url.includes('?') ? '&' : '?'}tr=${tr}` : url)
/** Poster frame for an ImageKit video, generated by ImageKit. */
export const ikPoster = (video: string, w = 1600) => (isIK(video) ? `${video.split('?')[0]}/ik-thumbnail.jpg?tr=w-${w}` : '')
