// ImageKit optimises on delivery: `tr` asks for a size, format (WebP/AVIF) and compression are automatic.
// Other files (e.g. the seeded /work images) pass through unchanged.
const isIK = (u: string) => /^https:\/\/[^/]*imagekit\.io\//.test(u)

export const ik = (url: string, tr: string) => (url && isIK(url) ? `${url}${url.includes('?') ? '&' : '?'}tr=${tr}` : url)

/** Poster frame for an ImageKit video, generated by ImageKit. */
export const ikPoster = (video: string, w = 1600) => (isIK(video) ? `${video.split('?')[0]}/ik-thumbnail.jpg?tr=w-${w}` : '')

export const isVideo = (u: string) => /\.(mp4|webm|mov)$/i.test(u)

export const isTouch = () => matchMedia('(pointer: coarse)').matches
