const envConstants = {
    PORT: 5000,
    NODE_ENV: 'development',
    MONGO_URI: 'mongodb://localhost:27017/codedemonss',
    CORS_ORIGIN: '*',
    ACCESS_TOKEN_SECRET: "super_secret_access_jwt_key_change_in_production",
    REFRESH_TOKEN_SECRET: "super_secret_refresh_jwt_key_change_in_production",
    BREVO_API_KEY: "",
    SENDING_USER: "codedemons <codedemons.in@gmail.com>",
    SEND_MAIL: false,
    CONTACT_EMAIL: "hello@codedemons.in",
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",
    GOOGLE_REDIRECT_URI: "http://localhost:5000/api/v1/auth/google/callback",
    FRONTEND_URL: "http://localhost:5173",
    IMAGEKIT_PUBLIC_KEY: "",
    IMAGEKIT_PRIVATE_KEY: "",
    IMAGEKIT_URL_ENDPOINT: "",
    IMAGEKIT_FOLDER: "/codedemons",
    ADMIN_EMAIL: "",
    ADMIN_PASSWORD: "",
    LICENSE_SECRET: "",
    UPI_ID: "",
    UPI_NAME: "codedemons",
    RAZORPAY_KEY_ID: "",
    RAZORPAY_KEY_SECRET: "",
} as const;

export default envConstants;
